name: ZZ

on: [workflow_dispatch]

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: HTML Validation
      run: |
        docker run --rm -v $PWD:/workspace w3c/unicorn /workspace/index.html
